### ISSUE TITLE
我个人使用没问题，就是需要安全的时候还是用官方的，但是用官方的一直遇到权限问题，不知道你遇到过吗？

### ISSUE THREAD

**Issue by 18827555809** [svcvit/dify-sandbox-py#2]
我在他的源码部分打了日志主要是在生成 `.so`文件的源码打印的日志：
`lib = ctypes.CDLL("/var/sandbox/sandbox-python/python.so")`
为了跟踪出错的地方。
在执行下面的脚本的时候：
`import ctypes
import json
import os
import sys
import traceback

os.environ["ALLOWED_SYSCALLS"] = ",".join([str(i) for i in range(999)]) # added by me

def excepthook(type, value, tb):
sys.stderr.write("".join(traceback.format_exception(type, value, tb)))
sys.stderr.flush()
sys.exit(-1)

sys.excepthook = excepthook

lib = ctypes.CDLL("/var/sandbox/sandbox-python/python.so")
lib.DifySeccomp.argtypes = [ctypes.c_uint32, ctypes.c_uint32, ctypes.c_bool]
lib.DifySeccomp.restype = None

import json
import os
import sys
import traceback

os.chdir("/var/sandbox/sandbox-python")

lib.DifySeccomp(65537, 1001, 1)

def main() -> dict:
return {"message": [1, 2, 3]}

from json import dumps, loads

output = main()

output = dumps(output, indent=4)

result = f"""<>
{output}
<>"""
print(result)
print(os.environ["ALLOWED_SYSCALLS"])

import numpy as np

print(np.version.full_version)`

日志跟踪显示lib.DifySeccomp(65537, 1001, 1)已经正常执行了，但是还是报错了
![image](https://github.com/user-attachments/assets/f905401d-087c-4ceb-9d0e-d57796d42d16)
感觉坑还是很多

**Comment by svcvit** [comment]
因为遇到报错也不知道从哪改起，所以做了现在这个简化版。官方sandbox的问题，需要在官方提issue哦
