### ISSUE TITLE
2024-11-25 17:20:18 exec ./start.sh: no such file or directory

### ISSUE THREAD

**Issue by maogeigei** [svcvit/dify-sandbox-py#3]
本地打包的镜像 docker 运行报错
![image](https://github.com/user-attachments/assets/18de2770-6ef3-468a-921f-a138a4b15ea4)

**Comment by svcvit** [comment]
是不是哪里操作有问题？在根目录下打包镜像哦，start.sh就在代码根目录

**Comment by maogeigei** [comment]
项目是要下载到那个路径吗，是在根目录打包的还是说找不到，打包后修改docker-compose.yaml，感觉应该读取不到.sh文件yaml没有这个路径的配置
![image](https://github.com/user-attachments/assets/ad2eeba8-f1ff-4b60-946b-4abbcf6c73e3)

**Comment by svcvit** [comment]
是下载本项目代码，在本项目里代码里打包镜像，start.sh是直接打包到镜像里的，你可以看下本项目镜像的Dockerfile源码。
