### ISSUE TITLE
为何每次重启要安装一次依赖呢？

### ISSUE THREAD

**Issue by leftchest** [svcvit/dify-sandbox-py#4]
<html>
<body>

2024/11/28 01:43:02 | stderr | INFO:     Started server process [1]
-- | -- | --
2024/11/28 01:43:00 | stderr | [notice] To update, run: pip install --upgrade pip
2024/11/28 01:43:00 | stderr | [notice] A new release of pip is available: 24.2 -> 24.3.1
2024/11/28 01:43:00 | stderr |  
2024/11/28 01:43:00 | stderr | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
2024/11/28 01:42:59 | stdout | 发现依赖文件，开始安装额外依赖...

</body>
</html>

**Comment by svcvit** [comment]
就是这么设计的……你如果有固定依赖，可以自己打包到镜像里
